<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;



class GradController extends Controller
{
    public function gradovi()
    {
        $gradovi=array_map(function($grad){
            return ["naziv"=>$grad['naziv'],'id'=>$grad['id']];
        }, self::$GRADOVI);

        return response()->json($gradovi);
    }

    public function opstine($idGrada)
    {
        $key = array_search($idGrada, array_column(self::$GRADOVI, 'id'));
        return response()->json(self::$GRADOVI[$key]['opstine']);

    }

    public static $GRADOVI =[
        ['naziv'=>'Beograd','id'=>'35112','opstine'=>[
            ['id'=>"528336", 'naziv'=>'Opština Barajevo','deloviOpstine'=>[
                ['id'=>"528338" , 'naziv'=>'Arnajevo'],
                ['id'=>"528339" , 'naziv'=>'Baćevac'],
                ['id'=>"528337" , 'naziv'=>'Barajevo (mesto)'],
                ['id'=>"528340" , 'naziv'=>'Bela reka'],
                ['id'=>"528341" , 'naziv'=>'Beljina'],
                ['id'=>"528342" , 'naziv'=>'Boždarevac'],
                ['id'=>"528343" , 'naziv'=>'Dražanovac'],
                ['id'=>"528344" , 'naziv'=>'Dubrave'],
                ['id'=>"528345" , 'naziv'=>'Glumčevo brdo'],
                ['id'=>"528346" , 'naziv'=>'Guncati'],
                ['id'=>"538006" , 'naziv'=>'Ibarska magistrala'],
                ['id'=>"528347" , 'naziv'=>'Karaula'],
                ['id'=>"528348" , 'naziv'=>'Lipovica'],
                ['id'=>"528349" , 'naziv'=>'Lipovička šuma'],
                ['id'=>"528350" , 'naziv'=>'Lisović'],
                ['id'=>"528351" , 'naziv'=>'Manić'],
                ['id'=>"528352" , 'naziv'=>'Meljak'],
                ['id'=>"528353" , 'naziv'=>'Nenadovac'],
                ['id'=>"528354" , 'naziv'=>'Pajšuma'],
                ['id'=>"528355" , 'naziv'=>'Rašića kraj'],
                ['id'=>"528356" , 'naziv'=>'Ravni gaj'],
                ['id'=>"528357" , 'naziv'=>'Rožanci'],
                ['id'=>"528358" , 'naziv'=>'Srednji kraj'],
                ['id'=>"528359" , 'naziv'=>'Stara Lipovica'],
                ['id'=>"528360" , 'naziv'=>'Suva šuma'],
                ['id'=>"528363" , 'naziv'=>'Šiljakovac'],
                ['id'=>"528361" , 'naziv'=>'Taraiš'],
                ['id'=>"528362" , 'naziv'=>'Trebež'],
                ['id'=>"528364" , 'naziv'=>'Veliki Borak'],
                ['id'=>"528365" , 'naziv'=>'Vitkovica'],
                ['id'=>"528366" , 'naziv'=>'Vranić'],
            ]],
            ['id'=>"40381", 'naziv'=>'Opština Čukarica','deloviOpstine'=>[
                ['id'=>"538101", 'naziv'=>  'Ada Ciganlija'],
                ['id'=>"534287", 'naziv'=>  'Banovo brdo'],
                ['id'=>"534465", 'naziv'=>  'Bele vode'],
                ['id'=>"538103", 'naziv'=>  'Careva Ćuprija'],
                ['id'=>"56357", 'naziv'=>  'Centar'],
                ['id'=>"534212", 'naziv'=>  'Cerak'],
                ['id'=>"534213", 'naziv'=>  'Cerak vinogradi'],
                ['id'=>"53031", 'naziv'=>  'Čukarička padina'],
                ['id'=>"53743", 'naziv'=>  'Filmski grad'],
                ['id'=>"534288", 'naziv'=>  'Golf'],
                ['id'=>"538003", 'naziv'=>  'Ibarska magistrala'],
                ['id'=>"54585", 'naziv'=>  'Julino brdo'],
                ['id'=>"534289", 'naziv'=>  'Košutnjak'],
                ['id'=>"55615", 'naziv'=>  'Makiš'],
                ['id'=>"538102", 'naziv'=>  'Novi Železnik'],
                ['id'=>"56400", 'naziv'=>  'Orlovača'],
                ['id'=>"56447", 'naziv'=>  'Ostružnica'],
                ['id'=>"56581", 'naziv'=>  'Pećani'],
                ['id'=>"534466", 'naziv'=>  'Repište'],
                ['id'=>"57340", 'naziv'=>  'Rucka'],
                ['id'=>"534467", 'naziv'=>  'Rupčine'],
                ['id'=>"57384", 'naziv'=>  'Rušanj'],
                ['id'=>"534470", 'naziv'=>  'Sremčica'],
                ['id'=>"534290", 'naziv'=>  'Sunčana padina'],
                ['id'=>"538225", 'naziv'=>  'Trgovačka'],
                ['id'=>"58612", 'naziv'=>  'Umka'],
                ['id'=>"58713", 'naziv'=>  'Velika Moštanica'],
                ['id'=>"347870", 'naziv'=>  'Vodovodska'],
                ['id'=>"534468", 'naziv'=>  'Žarkovo'],
                ['id'=>"534175", 'naziv'=>  'Železnik']
            ]],
            ['id'=>"530377", 'naziv'=>'Opština Grocka','deloviOpstine'=>[
                ['id'=>"530379" ,'naziv'=>'Begaljica'],
                ['id'=>"530380" ,'naziv'=>'Boleč'],
                ['id'=>"530381" ,'naziv'=>'Brestovik'],
                ['id'=>"530382" ,'naziv'=>'Dražanj'],
                ['id'=>"530378" ,'naziv'=>'Grocka (mesto)'],
                ['id'=>"530383" ,'naziv'=>'Kaluđerica'],
                ['id'=>"530384" ,'naziv'=>'Kamendol'],
                ['id'=>"530385" ,'naziv'=>'Leštane'],
                ['id'=>"530386" ,'naziv'=>'Plavinci'],
                ['id'=>"530387" ,'naziv'=>'Pudarci'],
                ['id'=>"530388" ,'naziv'=>'Radmilovac'],
                ['id'=>"530389" ,'naziv'=>'Ritopek'],
                ['id'=>"530390" ,'naziv'=>'Umčari'],
                ['id'=>"530391" ,'naziv'=>'Vinča'],
                ['id'=>"530392" ,'naziv'=>'Vrčin'],
                ['id'=>"530393" ,'naziv'=>'Zaklopača'],
                ['id'=>"530394" ,'naziv'=>'Živkovac']
            ]],
            ['id'=>"526435", 'naziv'=>'Opština Lazarevac','deloviOpstine'=>[
                ["id"=>"526437","naziv"=>"Arapovac"],
                ["id"=>"526438","naziv"=>"Baroševac"],
                ["id"=>"526439","naziv"=>"Barzilovica"],
                ["id"=>"526440","naziv"=>"Bistrica"],
                ["id"=>"526441","naziv"=>"Brajkovac"],
                ["id"=>"526442","naziv"=>"Burovo"],
                ["id"=>"526443","naziv"=>"Cvetovac"],
                ["id"=>"526444","naziv"=>"Čibutkovica"],
                ["id"=>"526445","naziv"=>"Ćelije"],
                ["id"=>"526446","naziv"=>"Dren"],
                ["id"=>"526447","naziv"=>"Dudovica"],
                ["id"=>"526448","naziv"=>"Junkovac"],
                ["id"=>"526449","naziv"=>"Kruševica"],
                ["id"=>"526436","naziv"=>"Lazarevac (mesto)"],
                ["id"=>"526450","naziv"=>"Leskovac"],
                ["id"=>"526451","naziv"=>"Lukavica"],
                ["id"=>"526452","naziv"=>"Mali Crljeni"],
                ["id"=>"526453","naziv"=>"Medoševac"],
                ["id"=>"526454","naziv"=>"Mirosaljci"],
                ["id"=>"526455","naziv"=>"Petka"],
                ["id"=>"526456","naziv"=>"Prkosava"],
                ["id"=>"526457","naziv"=>"Rudovci"],
                ["id"=>"526458","naziv"=>"Sokolovo"],
                ["id"=>"526459","naziv"=>"Stepojevac"],
                ["id"=>"526460","naziv"=>"Strmovo"],
                ["id"=>"526461","naziv"=>"Stubica"],
                ["id"=>"526462","naziv"=>"Šopić"],
                ["id"=>"526463","naziv"=>"Šušnjar"],
                ["id"=>"526464","naziv"=>"Trbušnica"],
                ["id"=>"526465","naziv"=>"Veliki Crljeni"],
                ["id"=>"526466","naziv"=>"Vrbovno"],
                ["id"=>"526467","naziv"=>"Vreoci"],
                ["id"=>"526468","naziv"=>"Zeoke"],
                ["id"=>"526469","naziv"=>"Županjac"],
            ]],
            ['id'=>"525616", 'naziv'=>'Opština Mladenovac','deloviOpstine'=>[
                ["id"=>"525618","naziv"=>"Amerić"],
                ["id"=>"525619","naziv"=>"Beluće"],
                ["id"=>"525620","naziv"=>"Crkvine"],
                ["id"=>"525621","naziv"=>"Dubona"],
                ["id"=>"525622","naziv"=>"Granice"],
                ["id"=>"525623","naziv"=>"Jagnjilo"],
                ["id"=>"525624","naziv"=>"Koraćica"],
                ["id"=>"525625","naziv"=>"Kovačevac"],
                ["id"=>"525626","naziv"=>"Mala Vrbica"],
                ["id"=>"525627","naziv"=>"Markovac"],
                ["id"=>"525628","naziv"=>"Međulužje"],
                ["id"=>"525617","naziv"=>"Mladenovac (mesto)"],
                ["id"=>"525629","naziv"=>"Mladenovac selo"],
                ["id"=>"525630","naziv"=>"Pružatovac"],
                ["id"=>"525631","naziv"=>"Rabrovac"],
                ["id"=>"525632","naziv"=>"Rajkovac"],
                ["id"=>"525633","naziv"=>"Selters Banja"],
                ["id"=>"525634","naziv"=>"Senaja"],
                ["id"=>"525635","naziv"=>"Šepšin"],
                ["id"=>"525636","naziv"=>"Velika Ivanča"],
                ["id"=>"525637","naziv"=>"Velika Krsna"],
                ["id"=>"525638","naziv"=>"Vlaška"],
            ]],
            ['id'=>"40574", 'naziv'=>'Opština Novi Beograd','deloviOpstine'=>[
                ["id"=>"51648","naziv"=>"Ada Međica"],
                ["id"=>"52161","naziv"=>"Arena"],
                ["id"=>"535589","naziv"=>"Bežanijska kosa 1"],
                ["id"=>"535590","naziv"=>"Bežanijska kosa 2"],
                ["id"=>"535591","naziv"=>"Bežanijska kosa 3"],
                ["id"=>"52153","naziv"=>"Blok 18 (Staro sajmište)"],
                ["id"=>"52155","naziv"=>"Blok 19a"],
                ["id"=>"52156","naziv"=>"Blok 2"],
                ["id"=>"52157","naziv"=>"Blok 21"],
                ["id"=>"52158","naziv"=>"Blok 22"],
                ["id"=>"52159","naziv"=>"Blok 23"],
                ["id"=>"52160","naziv"=>"Blok 24 (Super Vero)"],
                ["id"=>"537326","naziv"=>"Blok 26"],
                ["id"=>"52163","naziv"=>"Blok 28"],
                ["id"=>"52164","naziv"=>"Blok 29"],
                ["id"=>"52166","naziv"=>"Blok 3"],
                ["id"=>"52167","naziv"=>"Blok 30 (B92)"],
                ["id"=>"52169","naziv"=>"Blok 32 (Crkva svetog Dimitrija)"],
                ["id"=>"52170","naziv"=>"Blok 33"],
                ["id"=>"52171","naziv"=>"Blok 34 (Carina - Studentski grad)"],
                ["id"=>"321844","naziv"=>"Blok 35 (SC 11. april)"],
                ["id"=>"52174","naziv"=>"Blok 37"],
                ["id"=>"52175","naziv"=>"Blok 37a"],
                ["id"=>"52176","naziv"=>"Blok 38"],
                ["id"=>"345509","naziv"=>"Blok 39 (Fakultet dramskih umetnosti)"],
                ["id"=>"52177","naziv"=>"Blok 4 (Politehnička akademija)"],
                ["id"=>"535716","naziv"=>"Blok 40"],
                ["id"=>"52178","naziv"=>"Blok 41 (Expo centar)"],
                ["id"=>"52179","naziv"=>"Blok 41a (GTC)"],
                ["id"=>"537327","naziv"=>"Blok 42"],
                ["id"=>"321874","naziv"=>"Blok 43"],
                ["id"=>"52180","naziv"=>"Blok 44 (TC Piramida)"],
                ["id"=>"52182","naziv"=>"Blok 45 (TC Enjub)"],
                ["id"=>"52184","naziv"=>"Blok 5"],
                ["id"=>"321904","naziv"=>"Blok 53 (Kvantaš)"],
                ["id"=>"537328","naziv"=>"Blok 58"],
                ["id"=>"52185","naziv"=>"Blok 60"],
                ["id"=>"52186","naziv"=>"Blok 61"],
                ["id"=>"52187","naziv"=>"Blok 62"],
                ["id"=>"52188","naziv"=>"Blok 63"],
                ["id"=>"52190","naziv"=>"Blok 64"],
                ["id"=>"52191","naziv"=>"Blok 65 (West 65)"],
                ["id"=>"537329","naziv"=>"Blok 66"],
                ["id"=>"537330","naziv"=>"Blok 66a"],
                ["id"=>"52192","naziv"=>"Blok 67 (Belvil)"],
                ["id"=>"537331","naziv"=>"Blok 67a (A blok)"],
                ["id"=>"52193","naziv"=>"Blok 68"],
                ["id"=>"537332","naziv"=>"Blok 69"],
                ["id"=>"52195","naziv"=>"Blok 70 (kineski tržni centar)"],
                ["id"=>"52196","naziv"=>"Blok 70a"],
                ["id"=>"52205","naziv"=>"Blok 9a"],
                ["id"=>"53482","naziv"=>"Dr Ivana Ribara"],
                ["id"=>"52148","naziv"=>"Fontana"],
                ["id"=>"54310","naziv"=>"Hotel Hyatt"],
                ["id"=>"321814","naziv"=>"Hotel Jugoslavija"],
                ["id"=>"55297","naziv"=>"Ledine"],
                ["id"=>"52168","naziv"=>"Novi Merkator"],
                ["id"=>"52149","naziv"=>"Opština"],
                ["id"=>"56569","naziv"=>"Paviljoni"],
                ["id"=>"52154","naziv"=>"Sava centar"],
                ["id"=>"537334","naziv"=>"Savski nasip"],
                ["id"=>"535592","naziv"=>"Stara Bežanija"],
                ["id"=>"58067","naziv"=>"Stari Merkator"],
                ["id"=>"58447","naziv"=>"Tošin bunar"],
                ["id"=>"537333","naziv"=>"Ušće"],
                ["id"=>"52152","naziv"=>"YUBC"],
            ]],
            ['id'=>"529392", 'naziv'=>'Opština Obrenovac','deloviOpstine'=>[
                ["id"=>"529394","naziv"=>"Baljevac"],
                ["id"=>"529395","naziv"=>"Barič"],
                ["id"=>"529396","naziv"=>"Belo Polje"],
                ["id"=>"529397","naziv"=>"Brgulice"],
                ["id"=>"529398","naziv"=>"Brović"],
                ["id"=>"529399","naziv"=>"Draževac"],
                ["id"=>"529400","naziv"=>"Dren"],
                ["id"=>"529401","naziv"=>"Grabovac"],
                ["id"=>"529402","naziv"=>"Jasenak"],
                ["id"=>"529403","naziv"=>"Konatice"],
                ["id"=>"529404","naziv"=>"Krtinska"],
                ["id"=>"529405","naziv"=>"Ljubinić"],
                ["id"=>"529406","naziv"=>"Mala Moštanica"],
                ["id"=>"529407","naziv"=>"Mislođin"],
                ["id"=>"529393","naziv"=>"Obrenovac (mesto)"],
                ["id"=>"529408","naziv"=>"Orašac"],
                ["id"=>"529409","naziv"=>"Piroman"],
                ["id"=>"529410","naziv"=>"Poljane"],
                ["id"=>"529411","naziv"=>"Ratari"],
                ["id"=>"529412","naziv"=>"Rvati"],
                ["id"=>"529413","naziv"=>"Skela"],
                ["id"=>"529414","naziv"=>"Stubline"],
                ["id"=>"529415","naziv"=>"Trstenica"],
                ["id"=>"529416","naziv"=>"Urovci"],
                ["id"=>"529417","naziv"=>"Ušće"],
                ["id"=>"529418","naziv"=>"Veliko polje"],
                ["id"=>"529419","naziv"=>"Vukićevica"],
                ["id"=>"529420","naziv"=>"Zabrežje"],
                ["id"=>"529421","naziv"=>"Zvečka"],
            ]],
            ['id'=>"40761", 'naziv'=>'Opština Palilula','deloviOpstine'=>[
                ["id"=>"346984","naziv"=>"27. marta"],
                ["id"=>"51647","naziv"=>"Ada Huja"],
                ["id"=>"51976","naziv"=>"Bela stena"],
                ["id"=>"52240","naziv"=>"Bogoslovija"],
                ["id"=>"534800","naziv"=>"Borča"],
                ["id"=>"538105","naziv"=>"Borča Greda"],
                ["id"=>"52308","naziv"=>"Botanička bašta"],
                ["id"=>"346983","naziv"=>"Bulevar despota Stefana"],
                ["id"=>"56358","naziv"=>"Centar"],
                ["id"=>"346985","naziv"=>"Cvijićeva"],
                ["id"=>"534760","naziv"=>"Ćalije"],
                ["id"=>"538174","naziv"=>"Dalmatinska"],
                ["id"=>"53662","naziv"=>"Dunavski venac"],
                ["id"=>"54308","naziv"=>"Hadžipopovac"],
                ["id"=>"538104","naziv"=>"Hala Pionir"],
                ["id"=>"534724","naziv"=>"Karaburma"],
                ["id"=>"54978","naziv"=>"Kotež"],
                ["id"=>"55007","naziv"=>"Kovilovo"],
                ["id"=>"537335","naziv"=>"Kožara"],
                ["id"=>"534654","naziv"=>"Krnjača"],
                ["id"=>"534905","naziv"=>"Lešće"],
                ["id"=>"346980","naziv"=>"Mašinski fakultet"],
                ["id"=>"55896","naziv"=>"Mika Alas"],
                ["id"=>"534802","naziv"=>"Ovča"],
                ["id"=>"534688","naziv"=>"Padinska skela"],
                ["id"=>"346982","naziv"=>"Palilulska pijaca"],
                ["id"=>"56515","naziv"=>"Pančevački most"],
                ["id"=>"538005","naziv"=>"Pančevački put"],
                ["id"=>"346986","naziv"=>"Poštanska štedionica"],
                ["id"=>"56947","naziv"=>"Profesorska kolonija"],
                ["id"=>"57320","naziv"=>"Rospi ćuprija"],
                ["id"=>"538231","naziv"=>"Ruzveltova"],
                ["id"=>"57841","naziv"=>"Slanci"],
                ["id"=>"58352","naziv"=>"Tašmajdan"],
                ["id"=>"58768","naziv"=>"Veliko selo"],
                ["id"=>"58822","naziv"=>"Viline vode"],
                ["id"=>"534908","naziv"=>"Višnjica"],
                ["id"=>"534906","naziv"=>"Višnjička Banja"],
                ["id"=>"538106","naziv"=>"Višnjičko polje"],
                ["id"=>"538004","naziv"=>"Zrenjaninski put"],
            ]],
            ['id'=>"40769", 'naziv'=>'Opština Rakovica','deloviOpstine'=>[
                ["id"=>"56359","naziv"=>"Centar"],
                ["id"=>"538232","naziv"=>"Ibarska magistrala"],
                ["id"=>"54677","naziv"=>"Kanarevo brdo"],
                ["id"=>"531257","naziv"=>"Kijevo"],
                ["id"=>"531258","naziv"=>"Kneževac"],
                ["id"=>"55238","naziv"=>"Labudovo brdo"],
                ["id"=>"531122","naziv"=>"Miljakovac"],
                ["id"=>"56306","naziv"=>"Novo Skojevsko naselje"],
                ["id"=>"56627","naziv"=>"Petlovo brdo"],
                ["id"=>"531045","naziv"=>"Resnik"],
                ["id"=>"57817","naziv"=>"Skojevsko naselje"],
                ["id"=>"534416","naziv"=>"Stari Košutnjak"],
                ["id"=>"531079","naziv"=>"Vidikovac"],
                ["id"=>"531259","naziv"=>"Vidikovačka padina"],
            ]],
            ['id'=>"40772", 'naziv'=>'Opština Savski venac','deloviOpstine'=>[
                ["id"=>"347251","naziv"=>"Balkanska"],
                ["id"=>"51898","naziv"=>"Bara Venecija"],
                ["id"=>"538263","naziv"=>"Beograd na vodi"],
                ["id"=>"538172","naziv"=>"Beograđanka"],
                ["id"=>"347244","naziv"=>"Brankova"],
                ["id"=>"56360","naziv"=>"Centar"],
                ["id"=>"53106","naziv"=>"Dedinje"],
                ["id"=>"347247","naziv"=>"Ekonomski fakultet"],
                ["id"=>"347245","naziv"=>"Gavrila Principa"],
                ["id"=>"347243","naziv"=>"Humska"],
                ["id"=>"347252","naziv"=>"Karađorđeva"],
                ["id"=>"54793","naziv"=>"Klinički centar"],
                ["id"=>"347248","naziv"=>"Kneza Miloša"],
                ["id"=>"347242","naziv"=>"Kraljice Natalije"],
                ["id"=>"55403","naziv"=>"Lisičji potok"],
                ["id"=>"56051","naziv"=>"Mostarska petlja"],
                ["id"=>"347241","naziv"=>"Nemanjina"],
                ["id"=>"56489","naziv"=>"Palata pravde"],
                ["id"=>"56951","naziv"=>"Prokop"],
                ["id"=>"347240","naziv"=>"Resavska"],
                ["id"=>"57405","naziv"=>"Sajam"],
                ["id"=>"347250","naziv"=>"Sarajevska"],
                ["id"=>"57503","naziv"=>"Savski trg - Pristanište"],
                ["id"=>"321784","naziv"=>"Senjak"],
                ["id"=>"58002","naziv"=>"Stadion Crvene zvezde"],
                ["id"=>"347239","naziv"=>"Svetozara Markovića"],
                ["id"=>"58416","naziv"=>"Topčider"],
                ["id"=>"347246","naziv"=>"Višegradska"],
                ["id"=>"347249","naziv"=>"VMA"],

            ]],
            ['id'=>"527587", 'naziv'=>'Opština Sopot','deloviOpstine'=>[
                ["id"=>"527589","naziv"=>"Avala"],
                ["id"=>"527590","naziv"=>"Babe"],
                ["id"=>"527591","naziv"=>"Drlupa"],
                ["id"=>"527592","naziv"=>"Dučina"],
                ["id"=>"527593","naziv"=>"Đurinci"],
                ["id"=>"527594","naziv"=>"Guberevac"],
                ["id"=>"527595","naziv"=>"Kosmaj"],
                ["id"=>"527596","naziv"=>"Mala Ivanča"],
                ["id"=>"527597","naziv"=>"Mali Popović"],
                ["id"=>"527598","naziv"=>"Mali Požarevac"],
                ["id"=>"527599","naziv"=>"Nemenikuće"],
                ["id"=>"527600","naziv"=>"Parcani"],
                ["id"=>"527601","naziv"=>"Popović"],
                ["id"=>"527602","naziv"=>"Ralja"],
                ["id"=>"527603","naziv"=>"Rogača"],
                ["id"=>"527604","naziv"=>"Ropočevo"],
                ["id"=>"527605","naziv"=>"Sibnica"],
                ["id"=>"527606","naziv"=>"Slatina"],
                ["id"=>"527588","naziv"=>"Sopot (mesto)"],
                ["id"=>"527607","naziv"=>"Stojnik"],
            ]],
            ['id'=>"40776", 'naziv'=>'Opština Stari grad','deloviOpstine'=>[
                ["id"=>"531369","naziv"=>"25. maj"],
                ["id"=>"51698","naziv"=>"Andrićev venac"],
                ["id"=>"347629","naziv"=>"Atelje 212"],
                ["id"=>"531370","naziv"=>"Bajlonijeva pijaca"],
                ["id"=>"347634","naziv"=>"Cara Dušana"],
                ["id"=>"52684","naziv"=>"Centar"],
                ["id"=>"347627","naziv"=>"Dom omladine"],
                ["id"=>"531368","naziv"=>"Dorćol"],
                ["id"=>"531371","naziv"=>"Dunavski kej"],
                ["id"=>"347631","naziv"=>"Francuska"],
                ["id"=>"531372","naziv"=>"Gundulićev venac"],
                ["id"=>"54618","naziv"=>"Kalemegdan"],
                ["id"=>"54817","naziv"=>"Knez Mihailova"],
                ["id"=>"54902","naziv"=>"Kopitareva gradina"],
                ["id"=>"54936","naziv"=>"Kosančićev venac"],
                ["id"=>"347628","naziv"=>"Kralja Milana"],
                ["id"=>"347626","naziv"=>"Kralja Petra"],
                ["id"=>"55487","naziv"=>"London"],
                ["id"=>"347630","naziv"=>"Obilićev venac"],
                ["id"=>"347632","naziv"=>"Politika"],
                ["id"=>"57488","naziv"=>"Savamala"],
                ["id"=>"57809","naziv"=>"Skadarlija"],
                ["id"=>"57836","naziv"=>"Skupština"],
                ["id"=>"58198","naziv"=>"Studentski trg"],
                ["id"=>"347633","naziv"=>"Takovska"],
                ["id"=>"58376","naziv"=>"Terazije"],
                ["id"=>"58426","naziv"=>"Topličin venac"],
                ["id"=>"58481","naziv"=>"Trg Nikole Pašića"],
                ["id"=>"58482","naziv"=>"Trg Republike"],
                ["id"=>"59215","naziv"=>"Zeleni venac"],
            ]],
            ['id'=>"525206", 'naziv'=>'Opština Surčin','deloviOpstine'=>[
                ["id"=>"525208","naziv"=>"Bečmen"],
                ["id"=>"525209","naziv"=>"Boljevci"],
                ["id"=>"525210","naziv"=>"Dobanovci"],
                ["id"=>"525211","naziv"=>"Jakovo"],
                ["id"=>"525212","naziv"=>"Ključ"],
                ["id"=>"525213","naziv"=>"Petrovčić"],
                ["id"=>"525214","naziv"=>"Progar"],
                ["id"=>"525215","naziv"=>"Radiofar"],
                ["id"=>"525216","naziv"=>"Stremen"],
                ["id"=>"525207","naziv"=>"Surčin (mesto)"],
            ]],
            ['id'=>"40783", 'naziv'=>'Opština Voždovac','deloviOpstine'=>[
                ["id"=>"51721","naziv"=>"Autokomanda"],
                ["id"=>"535105","naziv"=>"Banjica"],
                ["id"=>"52001","naziv"=>"Beli potok"],
                ["id"=>"345987","naziv"=>"Bioskop Voždovac"],
                ["id"=>"535106","naziv"=>"Braće Jerković"],
                ["id"=>"52496","naziv"=>"Bubanj potok"],
                ["id"=>"345983","naziv"=>"Bulevar oslobođenja"],
                ["id"=>"537336","naziv"=>"Centar"],
                ["id"=>"345981","naziv"=>"Darvinova pošta"],
                ["id"=>"53699","naziv"=>"Dušanovac"],
                ["id"=>"345994","naziv"=>"Farmaceutski fakultet"],
                ["id"=>"345988","naziv"=>"FON - Bilećka"],
                ["id"=>"345986","naziv"=>"Franš"],
                ["id"=>"53761","naziv"=>"Gaj"],
                ["id"=>"345989","naziv"=>"Hotel M"],
                ["id"=>"535035","naziv"=>"Jajinci"],
                ["id"=>"345991","naziv"=>"Jove Ilića"],
                ["id"=>"535203","naziv"=>"Konjarnik"],
                ["id"=>"345992","naziv"=>"Kumodraška"],
                ["id"=>"535036","naziv"=>"Kumodraž"],
                ["id"=>"55298","naziv"=>"Lekino brdo"],
                ["id"=>"55769","naziv"=>"Marinkova bara"],
                ["id"=>"535199","naziv"=>"Medaković 1"],
                ["id"=>"535200","naziv"=>"Medaković 2"],
                ["id"=>"535201","naziv"=>"Medaković 3"],
                ["id"=>"535202","naziv"=>"Medaković padina"],
                ["id"=>"538107","naziv"=>"Naselje Stepa Stepanović"],
                ["id"=>"56659","naziv"=>"Pinosava"],
                ["id"=>"57114","naziv"=>"Rakovica selo"],
                ["id"=>"535198","naziv"=>"Ripanj"],
                ["id"=>"345985","naziv"=>"Saobraćajni fakultet"],
                ["id"=>"57803","naziv"=>"Siva stena"],
                ["id"=>"535197","naziv"=>"Šumice"],
                ["id"=>"58244","naziv"=>"Šuplja stena"],
                ["id"=>"58528","naziv"=>"Trošarina"],
                ["id"=>"535195","naziv"=>"Ustanička"],
                ["id"=>"345990","naziv"=>"Vitanovačka"],
                ["id"=>"535196","naziv"=>"Vojislava Ilića"],
                ["id"=>"58956","naziv"=>"Vojvode Stepe"],
                ["id"=>"538175","naziv"=>"Vojvode Vlahovića"],
                ["id"=>"345982","naziv"=>"Voždovačka crkva"],
                ["id"=>"345984","naziv"=>"Zaplanjska"],
                ["id"=>"59321","naziv"=>"Zuce"],
            ]],
            ['id'=>"40784", 'naziv'=>'Opština Vračar','deloviOpstine'=>[
                ["id"=>"346534","naziv"=>"Beogradska"],
                ["id"=>"321934","naziv"=>"Bulevar kralja Aleksandra"],
                ["id"=>"53009","naziv"=>"Crveni krst"],
                ["id"=>"53061","naziv"=>"Cvetni trg"],
                ["id"=>"53022","naziv"=>"Čubura"],
                ["id"=>"538173","naziv"=>"Gospodara Vučića"],
                ["id"=>"54175","naziv"=>"Gradić Pejton"],
                ["id"=>"54331","naziv"=>"Hram svetog Save"],
                ["id"=>"346530","naziv"=>"Južni bulevar"],
                ["id"=>"54620","naziv"=>"Kalenić pijaca"],
                ["id"=>"54695","naziv"=>"Karađorđev park"],
                ["id"=>"346533","naziv"=>"Krunska"],
                ["id"=>"538179","naziv"=>"Maksima Gorkog"],
                ["id"=>"56176","naziv"=>"Neimar"],
                ["id"=>"346532","naziv"=>"Pravni fakultet"],
                ["id"=>"346531","naziv"=>"SC Vračar"],
                ["id"=>"57869","naziv"=>"Slavija"],
            ]],
            ['id'=>"40787", 'naziv'=>'Opština Zemun','deloviOpstine'=>[
                ["id"=>"51691","naziv"=>"Altina"],
                ["id"=>"538007","naziv"=>"Autoput za Novi Sad"],
                ["id"=>"538002","naziv"=>"Autoput za Zagreb"],
                ["id"=>"51765","naziv"=>"Bački Ilovik"],
                ["id"=>"530948","naziv"=>"Batajnica"],
                ["id"=>"538001","naziv"=>"Batajnicki drum"],
                ["id"=>"346893","naziv"=>"Cara Dušana"],
                ["id"=>"59233","naziv"=>"Centar"],
                ["id"=>"53037","naziv"=>"Ćukovac"],
                ["id"=>"53430","naziv"=>"Donji grad"],
                ["id"=>"53769","naziv"=>"Galenika"],
                ["id"=>"53777","naziv"=>"Gardoš"],
                ["id"=>"54075","naziv"=>"Gornji grad"],
                ["id"=>"54134","naziv"=>"Goveđi brod"],
                ["id"=>"54527","naziv"=>"Jelovac"],
                ["id"=>"54645","naziv"=>"Kalvarija"],
                ["id"=>"54651","naziv"=>"Kamendin"],
                ["id"=>"530950","naziv"=>"Karađorđev trg"],
                ["id"=>"54738","naziv"=>"Kej"],
                ["id"=>"54859","naziv"=>"Kolonija Zmaj"],
                ["id"=>"55354","naziv"=>"Lido"],
                ["id"=>"55649","naziv"=>"Mala pruga"],
                ["id"=>"55764","naziv"=>"Marija Bursać"],
                ["id"=>"55808","naziv"=>"Meandri"],
                ["id"=>"56091","naziv"=>"Muhar"],
                ["id"=>"537337","naziv"=>"Naselje Sveti Sava"],
                ["id"=>"56243","naziv"=>"Novi grad"],
                ["id"=>"56696","naziv"=>"Plavi horizonti"],
                ["id"=>"538000","naziv"=>"Pregrevica"],
                ["id"=>"346894","naziv"=>"Prvomajska"],
                ["id"=>"57245","naziv"=>"Retenzija"],
                ["id"=>"57490","naziv"=>"Save Kovačevića"],
                ["id"=>"58274","naziv"=>"Sutjeska"],
                ["id"=>"346892","naziv"=>"Ugrinovačka"],
                ["id"=>"530949","naziv"=>"Ugrinovci"],
                ["id"=>"58948","naziv"=>"Vojni put"],
                ["id"=>"59234","naziv"=>"Zemun Bačka"],
                ["id"=>"59235","naziv"=>"Zemun polje"],
                ["id"=>"59222","naziv"=>"Železnička kolonija"],
            ]],
            ['id'=>"40788", 'naziv'=>'Opština Zvezdara','deloviOpstine'=>[
                ["id"=>"52561","naziv"=>"Bulbulder"],
                ["id"=>"52564","naziv"=>"Bulevar kralja Aleksandra"],
                ["id"=>"53057","naziv"=>"Cvetanova ćuprija"],
                ["id"=>"53060","naziv"=>"Cvetkova pijaca"],
                ["id"=>"535483","naziv"=>"Denkova bašta"],
                ["id"=>"53128","naziv"=>"Depo"],
                ["id"=>"346673","naziv"=>"Dimitrija Tucovića"],
                ["id"=>"53133","naziv"=>"Đeram pijaca"],
                ["id"=>"54191","naziv"=>"Gradska bolnica"],
                ["id"=>"54814","naziv"=>"Kluz"],
                ["id"=>"538276","naziv"=>"Konjarnik"],
                ["id"=>"55365","naziv"=>"Lion"],
                ["id"=>"55383","naziv"=>"Lipov lad"],
                ["id"=>"55690","naziv"=>"Mali Mokri Lug"],
                ["id"=>"531542","naziv"=>"Mirijevo"],
                ["id"=>"537339","naziv"=>"Novo groblje"],
                ["id"=>"56348","naziv"=>"Olimp"],
                ["id"=>"535484","naziv"=>"Rudo"],
                ["id"=>"346675","naziv"=>"Severni bulevar"],
                ["id"=>"57876","naziv"=>"Slavujev venac"],
                ["id"=>"538277","naziv"=>"Smederevski put"],
                ["id"=>"535485","naziv"=>"Učiteljsko naselje"],
                ["id"=>"58738","naziv"=>"Veliki Mokri Lug"],
                ["id"=>"59098","naziv"=>"Vukov Spomenik"],
                ["id"=>"59219","naziv"=>"Zeleno brdo"],
                ["id"=>"59345","naziv"=>"Zvezdara 2"],
                ["id"=>"346671","naziv"=>"Zvezdarska padina"],
                ["id"=>"59346","naziv"=>"Zvezdarska šuma"],
            ]],
        ]],
    ];
}



//zvezdara



